// Generated by gencpp from file iarc_msgs/GetData.msg
// DO NOT EDIT!


#ifndef IARC_MSGS_MESSAGE_GETDATA_H
#define IARC_MSGS_MESSAGE_GETDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iarc_msgs
{
template <class ContainerAllocator>
struct GetData_
{
  typedef GetData_<ContainerAllocator> Type;

  GetData_()
    : type()
    , data()  {
    }
  GetData_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::iarc_msgs::GetData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iarc_msgs::GetData_<ContainerAllocator> const> ConstPtr;

}; // struct GetData_

typedef ::iarc_msgs::GetData_<std::allocator<void> > GetData;

typedef boost::shared_ptr< ::iarc_msgs::GetData > GetDataPtr;
typedef boost::shared_ptr< ::iarc_msgs::GetData const> GetDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iarc_msgs::GetData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iarc_msgs::GetData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iarc_msgs::GetData_<ContainerAllocator1> & lhs, const ::iarc_msgs::GetData_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iarc_msgs::GetData_<ContainerAllocator1> & lhs, const ::iarc_msgs::GetData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iarc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::GetData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::GetData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::GetData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::GetData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::GetData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::GetData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iarc_msgs::GetData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "167124529e10dda68e69162baeaee3b8";
  }

  static const char* value(const ::iarc_msgs::GetData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x167124529e10dda6ULL;
  static const uint64_t static_value2 = 0x8e69162baeaee3b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::iarc_msgs::GetData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iarc_msgs/GetData";
  }

  static const char* value(const ::iarc_msgs::GetData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iarc_msgs::GetData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type\n"
"string data\n"
;
  }

  static const char* value(const ::iarc_msgs::GetData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iarc_msgs::GetData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iarc_msgs::GetData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iarc_msgs::GetData_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IARC_MSGS_MESSAGE_GETDATA_H
