// Generated by gencpp from file iarc_msgs/HandSignal.msg
// DO NOT EDIT!


#ifndef IARC_MSGS_MESSAGE_HANDSIGNAL_H
#define IARC_MSGS_MESSAGE_HANDSIGNAL_H

#include <ros/service_traits.h>


#include <iarc_msgs/HandSignalRequest.h>
#include <iarc_msgs/HandSignalResponse.h>


namespace iarc_msgs
{

struct HandSignal
{

typedef HandSignalRequest Request;
typedef HandSignalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HandSignal
} // namespace iarc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iarc_msgs::HandSignal > {
  static const char* value()
  {
    return "66389ecef7e0d1c6c3fdf9137ae8737e";
  }

  static const char* value(const ::iarc_msgs::HandSignal&) { return value(); }
};

template<>
struct DataType< ::iarc_msgs::HandSignal > {
  static const char* value()
  {
    return "iarc_msgs/HandSignal";
  }

  static const char* value(const ::iarc_msgs::HandSignal&) { return value(); }
};


// service_traits::MD5Sum< ::iarc_msgs::HandSignalRequest> should match
// service_traits::MD5Sum< ::iarc_msgs::HandSignal >
template<>
struct MD5Sum< ::iarc_msgs::HandSignalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iarc_msgs::HandSignal >::value();
  }
  static const char* value(const ::iarc_msgs::HandSignalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iarc_msgs::HandSignalRequest> should match
// service_traits::DataType< ::iarc_msgs::HandSignal >
template<>
struct DataType< ::iarc_msgs::HandSignalRequest>
{
  static const char* value()
  {
    return DataType< ::iarc_msgs::HandSignal >::value();
  }
  static const char* value(const ::iarc_msgs::HandSignalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iarc_msgs::HandSignalResponse> should match
// service_traits::MD5Sum< ::iarc_msgs::HandSignal >
template<>
struct MD5Sum< ::iarc_msgs::HandSignalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iarc_msgs::HandSignal >::value();
  }
  static const char* value(const ::iarc_msgs::HandSignalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iarc_msgs::HandSignalResponse> should match
// service_traits::DataType< ::iarc_msgs::HandSignal >
template<>
struct DataType< ::iarc_msgs::HandSignalResponse>
{
  static const char* value()
  {
    return DataType< ::iarc_msgs::HandSignal >::value();
  }
  static const char* value(const ::iarc_msgs::HandSignalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IARC_MSGS_MESSAGE_HANDSIGNAL_H
