// Generated by gencpp from file iarc_msgs/HandSignalRequest.msg
// DO NOT EDIT!


#ifndef IARC_MSGS_MESSAGE_HANDSIGNALREQUEST_H
#define IARC_MSGS_MESSAGE_HANDSIGNALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iarc_msgs
{
template <class ContainerAllocator>
struct HandSignalRequest_
{
  typedef HandSignalRequest_<ContainerAllocator> Type;

  HandSignalRequest_()
    {
    }
  HandSignalRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HandSignalRequest_

typedef ::iarc_msgs::HandSignalRequest_<std::allocator<void> > HandSignalRequest;

typedef boost::shared_ptr< ::iarc_msgs::HandSignalRequest > HandSignalRequestPtr;
typedef boost::shared_ptr< ::iarc_msgs::HandSignalRequest const> HandSignalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iarc_msgs::HandSignalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace iarc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::iarc_msgs::HandSignalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iarc_msgs/HandSignalRequest";
  }

  static const char* value(const ::iarc_msgs::HandSignalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::iarc_msgs::HandSignalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandSignalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iarc_msgs::HandSignalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::iarc_msgs::HandSignalRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // IARC_MSGS_MESSAGE_HANDSIGNALREQUEST_H
