// Generated by gencpp from file iarc_msgs/QRMatrix.msg
// DO NOT EDIT!


#ifndef IARC_MSGS_MESSAGE_QRMATRIX_H
#define IARC_MSGS_MESSAGE_QRMATRIX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iarc_msgs
{
template <class ContainerAllocator>
struct QRMatrix_
{
  typedef QRMatrix_<ContainerAllocator> Type;

  QRMatrix_()
    : matrix()  {
      matrix.assign(0);
  }
  QRMatrix_(const ContainerAllocator& _alloc)
    : matrix()  {
  (void)_alloc;
      matrix.assign(0);
  }



   typedef boost::array<int64_t, 121>  _matrix_type;
  _matrix_type matrix;





  typedef boost::shared_ptr< ::iarc_msgs::QRMatrix_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iarc_msgs::QRMatrix_<ContainerAllocator> const> ConstPtr;

}; // struct QRMatrix_

typedef ::iarc_msgs::QRMatrix_<std::allocator<void> > QRMatrix;

typedef boost::shared_ptr< ::iarc_msgs::QRMatrix > QRMatrixPtr;
typedef boost::shared_ptr< ::iarc_msgs::QRMatrix const> QRMatrixConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iarc_msgs::QRMatrix_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iarc_msgs::QRMatrix_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iarc_msgs::QRMatrix_<ContainerAllocator1> & lhs, const ::iarc_msgs::QRMatrix_<ContainerAllocator2> & rhs)
{
  return lhs.matrix == rhs.matrix;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iarc_msgs::QRMatrix_<ContainerAllocator1> & lhs, const ::iarc_msgs::QRMatrix_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iarc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::QRMatrix_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::QRMatrix_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::QRMatrix_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::QRMatrix_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::QRMatrix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::QRMatrix_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iarc_msgs::QRMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6613d284da8b77ddadc769d602bc297f";
  }

  static const char* value(const ::iarc_msgs::QRMatrix_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6613d284da8b77ddULL;
  static const uint64_t static_value2 = 0xadc769d602bc297fULL;
};

template<class ContainerAllocator>
struct DataType< ::iarc_msgs::QRMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iarc_msgs/QRMatrix";
  }

  static const char* value(const ::iarc_msgs::QRMatrix_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iarc_msgs::QRMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[121] matrix\n"
;
  }

  static const char* value(const ::iarc_msgs::QRMatrix_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iarc_msgs::QRMatrix_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.matrix);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QRMatrix_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iarc_msgs::QRMatrix_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iarc_msgs::QRMatrix_<ContainerAllocator>& v)
  {
    s << indent << "matrix[]" << std::endl;
    for (size_t i = 0; i < v.matrix.size(); ++i)
    {
      s << indent << "  matrix[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.matrix[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IARC_MSGS_MESSAGE_QRMATRIX_H
