// Generated by gencpp from file iarc_msgs/QuadState.msg
// DO NOT EDIT!


#ifndef IARC_MSGS_MESSAGE_QUADSTATE_H
#define IARC_MSGS_MESSAGE_QUADSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iarc_msgs
{
template <class ContainerAllocator>
struct QuadState_
{
  typedef QuadState_<ContainerAllocator> Type;

  QuadState_()
    : quad_state(0)  {
    }
  QuadState_(const ContainerAllocator& _alloc)
    : quad_state(0)  {
  (void)_alloc;
    }



   typedef int8_t _quad_state_type;
  _quad_state_type quad_state;





  typedef boost::shared_ptr< ::iarc_msgs::QuadState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iarc_msgs::QuadState_<ContainerAllocator> const> ConstPtr;

}; // struct QuadState_

typedef ::iarc_msgs::QuadState_<std::allocator<void> > QuadState;

typedef boost::shared_ptr< ::iarc_msgs::QuadState > QuadStatePtr;
typedef boost::shared_ptr< ::iarc_msgs::QuadState const> QuadStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iarc_msgs::QuadState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iarc_msgs::QuadState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iarc_msgs::QuadState_<ContainerAllocator1> & lhs, const ::iarc_msgs::QuadState_<ContainerAllocator2> & rhs)
{
  return lhs.quad_state == rhs.quad_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iarc_msgs::QuadState_<ContainerAllocator1> & lhs, const ::iarc_msgs::QuadState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iarc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::QuadState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::QuadState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::QuadState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::QuadState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::QuadState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::QuadState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iarc_msgs::QuadState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49b8231aaa41ecfdd614616186a40519";
  }

  static const char* value(const ::iarc_msgs::QuadState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49b8231aaa41ecfdULL;
  static const uint64_t static_value2 = 0xd614616186a40519ULL;
};

template<class ContainerAllocator>
struct DataType< ::iarc_msgs::QuadState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iarc_msgs/QuadState";
  }

  static const char* value(const ::iarc_msgs::QuadState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iarc_msgs::QuadState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 quad_state\n"
;
  }

  static const char* value(const ::iarc_msgs::QuadState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iarc_msgs::QuadState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.quad_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iarc_msgs::QuadState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iarc_msgs::QuadState_<ContainerAllocator>& v)
  {
    s << indent << "quad_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.quad_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IARC_MSGS_MESSAGE_QUADSTATE_H
