// Generated by gencpp from file iarc_msgs/QuadVelocity.msg
// DO NOT EDIT!


#ifndef IARC_MSGS_MESSAGE_QUADVELOCITY_H
#define IARC_MSGS_MESSAGE_QUADVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iarc_msgs
{
template <class ContainerAllocator>
struct QuadVelocity_
{
  typedef QuadVelocity_<ContainerAllocator> Type;

  QuadVelocity_()
    : vx(0.0)
    , vy(0.0)  {
    }
  QuadVelocity_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)  {
  (void)_alloc;
    }



   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;





  typedef boost::shared_ptr< ::iarc_msgs::QuadVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iarc_msgs::QuadVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct QuadVelocity_

typedef ::iarc_msgs::QuadVelocity_<std::allocator<void> > QuadVelocity;

typedef boost::shared_ptr< ::iarc_msgs::QuadVelocity > QuadVelocityPtr;
typedef boost::shared_ptr< ::iarc_msgs::QuadVelocity const> QuadVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iarc_msgs::QuadVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iarc_msgs::QuadVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iarc_msgs::QuadVelocity_<ContainerAllocator1> & lhs, const ::iarc_msgs::QuadVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iarc_msgs::QuadVelocity_<ContainerAllocator1> & lhs, const ::iarc_msgs::QuadVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iarc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::QuadVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::QuadVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::QuadVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::QuadVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::QuadVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::QuadVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iarc_msgs::QuadVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95d7cdcc3a89a9361eb29eff06cd1058";
  }

  static const char* value(const ::iarc_msgs::QuadVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95d7cdcc3a89a936ULL;
  static const uint64_t static_value2 = 0x1eb29eff06cd1058ULL;
};

template<class ContainerAllocator>
struct DataType< ::iarc_msgs::QuadVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iarc_msgs/QuadVelocity";
  }

  static const char* value(const ::iarc_msgs::QuadVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iarc_msgs::QuadVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 vx\n"
"float64 vy\n"
;
  }

  static const char* value(const ::iarc_msgs::QuadVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iarc_msgs::QuadVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iarc_msgs::QuadVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iarc_msgs::QuadVelocity_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IARC_MSGS_MESSAGE_QUADVELOCITY_H
