// Generated by gencpp from file iarc_msgs/SendQRMatrix.msg
// DO NOT EDIT!


#ifndef IARC_MSGS_MESSAGE_SENDQRMATRIX_H
#define IARC_MSGS_MESSAGE_SENDQRMATRIX_H

#include <ros/service_traits.h>


#include <iarc_msgs/SendQRMatrixRequest.h>
#include <iarc_msgs/SendQRMatrixResponse.h>


namespace iarc_msgs
{

struct SendQRMatrix
{

typedef SendQRMatrixRequest Request;
typedef SendQRMatrixResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendQRMatrix
} // namespace iarc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iarc_msgs::SendQRMatrix > {
  static const char* value()
  {
    return "fd173312d52f41d9b2e7080c044e0769";
  }

  static const char* value(const ::iarc_msgs::SendQRMatrix&) { return value(); }
};

template<>
struct DataType< ::iarc_msgs::SendQRMatrix > {
  static const char* value()
  {
    return "iarc_msgs/SendQRMatrix";
  }

  static const char* value(const ::iarc_msgs::SendQRMatrix&) { return value(); }
};


// service_traits::MD5Sum< ::iarc_msgs::SendQRMatrixRequest> should match
// service_traits::MD5Sum< ::iarc_msgs::SendQRMatrix >
template<>
struct MD5Sum< ::iarc_msgs::SendQRMatrixRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iarc_msgs::SendQRMatrix >::value();
  }
  static const char* value(const ::iarc_msgs::SendQRMatrixRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iarc_msgs::SendQRMatrixRequest> should match
// service_traits::DataType< ::iarc_msgs::SendQRMatrix >
template<>
struct DataType< ::iarc_msgs::SendQRMatrixRequest>
{
  static const char* value()
  {
    return DataType< ::iarc_msgs::SendQRMatrix >::value();
  }
  static const char* value(const ::iarc_msgs::SendQRMatrixRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iarc_msgs::SendQRMatrixResponse> should match
// service_traits::MD5Sum< ::iarc_msgs::SendQRMatrix >
template<>
struct MD5Sum< ::iarc_msgs::SendQRMatrixResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iarc_msgs::SendQRMatrix >::value();
  }
  static const char* value(const ::iarc_msgs::SendQRMatrixResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iarc_msgs::SendQRMatrixResponse> should match
// service_traits::DataType< ::iarc_msgs::SendQRMatrix >
template<>
struct DataType< ::iarc_msgs::SendQRMatrixResponse>
{
  static const char* value()
  {
    return DataType< ::iarc_msgs::SendQRMatrix >::value();
  }
  static const char* value(const ::iarc_msgs::SendQRMatrixResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IARC_MSGS_MESSAGE_SENDQRMATRIX_H
