// Generated by gencpp from file iarc_msgs/SendQRCodeRequest.msg
// DO NOT EDIT!


#ifndef IARC_MSGS_MESSAGE_SENDQRCODEREQUEST_H
#define IARC_MSGS_MESSAGE_SENDQRCODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iarc_msgs
{
template <class ContainerAllocator>
struct SendQRCodeRequest_
{
  typedef SendQRCodeRequest_<ContainerAllocator> Type;

  SendQRCodeRequest_()
    : channel(0)
    , code()  {
      code.assign(0);
  }
  SendQRCodeRequest_(const ContainerAllocator& _alloc)
    : channel(0)
    , code()  {
  (void)_alloc;
      code.assign(0);
  }



   typedef int64_t _channel_type;
  _channel_type channel;

   typedef boost::array<int64_t, 4>  _code_type;
  _code_type code;





  typedef boost::shared_ptr< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendQRCodeRequest_

typedef ::iarc_msgs::SendQRCodeRequest_<std::allocator<void> > SendQRCodeRequest;

typedef boost::shared_ptr< ::iarc_msgs::SendQRCodeRequest > SendQRCodeRequestPtr;
typedef boost::shared_ptr< ::iarc_msgs::SendQRCodeRequest const> SendQRCodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator1> & lhs, const ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.channel == rhs.channel &&
    lhs.code == rhs.code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator1> & lhs, const ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iarc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "704927ff9a6f6a65583495f8609d3df5";
  }

  static const char* value(const ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x704927ff9a6f6a65ULL;
  static const uint64_t static_value2 = 0x583495f8609d3df5ULL;
};

template<class ContainerAllocator>
struct DataType< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iarc_msgs/SendQRCodeRequest";
  }

  static const char* value(const ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 channel\n"
"int64[4] code\n"
;
  }

  static const char* value(const ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel);
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendQRCodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iarc_msgs::SendQRCodeRequest_<ContainerAllocator>& v)
  {
    s << indent << "channel: ";
    Printer<int64_t>::stream(s, indent + "  ", v.channel);
    s << indent << "code[]" << std::endl;
    for (size_t i = 0; i < v.code.size(); ++i)
    {
      s << indent << "  code[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.code[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IARC_MSGS_MESSAGE_SENDQRCODEREQUEST_H
