// Generated by gencpp from file iarc_msgs/SendPose.msg
// DO NOT EDIT!


#ifndef IARC_MSGS_MESSAGE_SENDPOSE_H
#define IARC_MSGS_MESSAGE_SENDPOSE_H

#include <ros/service_traits.h>


#include <iarc_msgs/SendPoseRequest.h>
#include <iarc_msgs/SendPoseResponse.h>


namespace iarc_msgs
{

struct SendPose
{

typedef SendPoseRequest Request;
typedef SendPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendPose
} // namespace iarc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iarc_msgs::SendPose > {
  static const char* value()
  {
    return "b6c3c7224290d99a0f16ac88a57622f1";
  }

  static const char* value(const ::iarc_msgs::SendPose&) { return value(); }
};

template<>
struct DataType< ::iarc_msgs::SendPose > {
  static const char* value()
  {
    return "iarc_msgs/SendPose";
  }

  static const char* value(const ::iarc_msgs::SendPose&) { return value(); }
};


// service_traits::MD5Sum< ::iarc_msgs::SendPoseRequest> should match
// service_traits::MD5Sum< ::iarc_msgs::SendPose >
template<>
struct MD5Sum< ::iarc_msgs::SendPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iarc_msgs::SendPose >::value();
  }
  static const char* value(const ::iarc_msgs::SendPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iarc_msgs::SendPoseRequest> should match
// service_traits::DataType< ::iarc_msgs::SendPose >
template<>
struct DataType< ::iarc_msgs::SendPoseRequest>
{
  static const char* value()
  {
    return DataType< ::iarc_msgs::SendPose >::value();
  }
  static const char* value(const ::iarc_msgs::SendPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iarc_msgs::SendPoseResponse> should match
// service_traits::MD5Sum< ::iarc_msgs::SendPose >
template<>
struct MD5Sum< ::iarc_msgs::SendPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iarc_msgs::SendPose >::value();
  }
  static const char* value(const ::iarc_msgs::SendPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iarc_msgs::SendPoseResponse> should match
// service_traits::DataType< ::iarc_msgs::SendPose >
template<>
struct DataType< ::iarc_msgs::SendPoseResponse>
{
  static const char* value()
  {
    return DataType< ::iarc_msgs::SendPose >::value();
  }
  static const char* value(const ::iarc_msgs::SendPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IARC_MSGS_MESSAGE_SENDPOSE_H
