// Generated by gencpp from file iarc_msgs/SendCommand.msg
// DO NOT EDIT!


#ifndef IARC_MSGS_MESSAGE_SENDCOMMAND_H
#define IARC_MSGS_MESSAGE_SENDCOMMAND_H

#include <ros/service_traits.h>


#include <iarc_msgs/SendCommandRequest.h>
#include <iarc_msgs/SendCommandResponse.h>


namespace iarc_msgs
{

struct SendCommand
{

typedef SendCommandRequest Request;
typedef SendCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendCommand
} // namespace iarc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iarc_msgs::SendCommand > {
  static const char* value()
  {
    return "23fbd02f00f51588a9ba39cc1ae0975a";
  }

  static const char* value(const ::iarc_msgs::SendCommand&) { return value(); }
};

template<>
struct DataType< ::iarc_msgs::SendCommand > {
  static const char* value()
  {
    return "iarc_msgs/SendCommand";
  }

  static const char* value(const ::iarc_msgs::SendCommand&) { return value(); }
};


// service_traits::MD5Sum< ::iarc_msgs::SendCommandRequest> should match
// service_traits::MD5Sum< ::iarc_msgs::SendCommand >
template<>
struct MD5Sum< ::iarc_msgs::SendCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iarc_msgs::SendCommand >::value();
  }
  static const char* value(const ::iarc_msgs::SendCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iarc_msgs::SendCommandRequest> should match
// service_traits::DataType< ::iarc_msgs::SendCommand >
template<>
struct DataType< ::iarc_msgs::SendCommandRequest>
{
  static const char* value()
  {
    return DataType< ::iarc_msgs::SendCommand >::value();
  }
  static const char* value(const ::iarc_msgs::SendCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iarc_msgs::SendCommandResponse> should match
// service_traits::MD5Sum< ::iarc_msgs::SendCommand >
template<>
struct MD5Sum< ::iarc_msgs::SendCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iarc_msgs::SendCommand >::value();
  }
  static const char* value(const ::iarc_msgs::SendCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iarc_msgs::SendCommandResponse> should match
// service_traits::DataType< ::iarc_msgs::SendCommand >
template<>
struct DataType< ::iarc_msgs::SendCommandResponse>
{
  static const char* value()
  {
    return DataType< ::iarc_msgs::SendCommand >::value();
  }
  static const char* value(const ::iarc_msgs::SendCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IARC_MSGS_MESSAGE_SENDCOMMAND_H
