// Generated by gencpp from file iarc_msgs/SendQRMatrixResponse.msg
// DO NOT EDIT!


#ifndef IARC_MSGS_MESSAGE_SENDQRMATRIXRESPONSE_H
#define IARC_MSGS_MESSAGE_SENDQRMATRIXRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iarc_msgs
{
template <class ContainerAllocator>
struct SendQRMatrixResponse_
{
  typedef SendQRMatrixResponse_<ContainerAllocator> Type;

  SendQRMatrixResponse_()
    : feedback(false)  {
    }
  SendQRMatrixResponse_(const ContainerAllocator& _alloc)
    : feedback(false)  {
  (void)_alloc;
    }



   typedef uint8_t _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SendQRMatrixResponse_

typedef ::iarc_msgs::SendQRMatrixResponse_<std::allocator<void> > SendQRMatrixResponse;

typedef boost::shared_ptr< ::iarc_msgs::SendQRMatrixResponse > SendQRMatrixResponsePtr;
typedef boost::shared_ptr< ::iarc_msgs::SendQRMatrixResponse const> SendQRMatrixResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator1> & lhs, const ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator1> & lhs, const ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iarc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1f168a39479bedb24dba7a087426182";
  }

  static const char* value(const ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1f168a39479bedbULL;
  static const uint64_t static_value2 = 0x24dba7a087426182ULL;
};

template<class ContainerAllocator>
struct DataType< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iarc_msgs/SendQRMatrixResponse";
  }

  static const char* value(const ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool feedback\n"
"\n"
;
  }

  static const char* value(const ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendQRMatrixResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iarc_msgs::SendQRMatrixResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IARC_MSGS_MESSAGE_SENDQRMATRIXRESPONSE_H
