// Generated by gencpp from file iarc_msgs/Start_QRScan.msg
// DO NOT EDIT!


#ifndef IARC_MSGS_MESSAGE_START_QRSCAN_H
#define IARC_MSGS_MESSAGE_START_QRSCAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iarc_msgs
{
template <class ContainerAllocator>
struct Start_QRScan_
{
  typedef Start_QRScan_<ContainerAllocator> Type;

  Start_QRScan_()
    : start_qrscan(0)  {
    }
  Start_QRScan_(const ContainerAllocator& _alloc)
    : start_qrscan(0)  {
  (void)_alloc;
    }



   typedef int8_t _start_qrscan_type;
  _start_qrscan_type start_qrscan;





  typedef boost::shared_ptr< ::iarc_msgs::Start_QRScan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iarc_msgs::Start_QRScan_<ContainerAllocator> const> ConstPtr;

}; // struct Start_QRScan_

typedef ::iarc_msgs::Start_QRScan_<std::allocator<void> > Start_QRScan;

typedef boost::shared_ptr< ::iarc_msgs::Start_QRScan > Start_QRScanPtr;
typedef boost::shared_ptr< ::iarc_msgs::Start_QRScan const> Start_QRScanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iarc_msgs::Start_QRScan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iarc_msgs::Start_QRScan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iarc_msgs::Start_QRScan_<ContainerAllocator1> & lhs, const ::iarc_msgs::Start_QRScan_<ContainerAllocator2> & rhs)
{
  return lhs.start_qrscan == rhs.start_qrscan;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iarc_msgs::Start_QRScan_<ContainerAllocator1> & lhs, const ::iarc_msgs::Start_QRScan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iarc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::Start_QRScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_msgs::Start_QRScan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::Start_QRScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_msgs::Start_QRScan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::Start_QRScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_msgs::Start_QRScan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iarc_msgs::Start_QRScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88694611e19cf8dc57b2f35c3cd23ec9";
  }

  static const char* value(const ::iarc_msgs::Start_QRScan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88694611e19cf8dcULL;
  static const uint64_t static_value2 = 0x57b2f35c3cd23ec9ULL;
};

template<class ContainerAllocator>
struct DataType< ::iarc_msgs::Start_QRScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iarc_msgs/Start_QRScan";
  }

  static const char* value(const ::iarc_msgs::Start_QRScan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iarc_msgs::Start_QRScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 start_qrscan\n"
;
  }

  static const char* value(const ::iarc_msgs::Start_QRScan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iarc_msgs::Start_QRScan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_qrscan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Start_QRScan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iarc_msgs::Start_QRScan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iarc_msgs::Start_QRScan_<ContainerAllocator>& v)
  {
    s << indent << "start_qrscan: ";
    Printer<int8_t>::stream(s, indent + "  ", v.start_qrscan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IARC_MSGS_MESSAGE_START_QRSCAN_H
